// Generated by Futhark 0.21.11
// git: 662b2221cfe846f94b7d4521ca2b5e419fe69223
#pragma once


// Headers\n")
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <float.h>

#ifdef __cplusplus
extern "C" {
#endif

// Initialisation
struct futhark_context_config;
struct futhark_context_config *futhark_context_config_new(void);
void futhark_context_config_free(struct futhark_context_config *cfg);
void futhark_context_config_set_debugging(struct futhark_context_config *cfg,
                                          int flag);
void futhark_context_config_set_profiling(struct futhark_context_config *cfg,
                                          int flag);
void futhark_context_config_set_logging(struct futhark_context_config *cfg,
                                        int flag);
struct futhark_context;
struct futhark_context *futhark_context_new(struct futhark_context_config *cfg);
void futhark_context_free(struct futhark_context *ctx);
int futhark_context_config_set_tuning_param(struct futhark_context_config *cfg,
                                            const char *param_name,
                                            size_t param_value);
int futhark_get_tuning_param_count(void);
const char *futhark_get_tuning_param_name(int);
const char *futhark_get_tuning_param_class(int);

// Arrays
struct futhark_f32_3d;
struct futhark_f32_3d *futhark_new_f32_3d(struct futhark_context *ctx, const
                                          float *data, int64_t dim0,
                                          int64_t dim1, int64_t dim2);
struct futhark_f32_3d *futhark_new_raw_f32_3d(struct futhark_context *ctx, const
                                              unsigned char *data,
                                              int64_t offset, int64_t dim0,
                                              int64_t dim1, int64_t dim2);
int futhark_free_f32_3d(struct futhark_context *ctx,
                        struct futhark_f32_3d *arr);
int futhark_values_f32_3d(struct futhark_context *ctx,
                          struct futhark_f32_3d *arr, float *data);
unsigned char *futhark_values_raw_f32_3d(struct futhark_context *ctx,
                                         struct futhark_f32_3d *arr);
const int64_t *futhark_shape_f32_3d(struct futhark_context *ctx,
                                    struct futhark_f32_3d *arr);
struct futhark_f64_4d;
struct futhark_f64_4d *futhark_new_f64_4d(struct futhark_context *ctx, const
                                          double *data, int64_t dim0,
                                          int64_t dim1, int64_t dim2,
                                          int64_t dim3);
struct futhark_f64_4d *futhark_new_raw_f64_4d(struct futhark_context *ctx, const
                                              unsigned char *data,
                                              int64_t offset, int64_t dim0,
                                              int64_t dim1, int64_t dim2,
                                              int64_t dim3);
int futhark_free_f64_4d(struct futhark_context *ctx,
                        struct futhark_f64_4d *arr);
int futhark_values_f64_4d(struct futhark_context *ctx,
                          struct futhark_f64_4d *arr, double *data);
unsigned char *futhark_values_raw_f64_4d(struct futhark_context *ctx,
                                         struct futhark_f64_4d *arr);
const int64_t *futhark_shape_f64_4d(struct futhark_context *ctx,
                                    struct futhark_f64_4d *arr);

// Opaque values


// Entry points
int futhark_entry_densityFilter(struct futhark_context *ctx,
                                struct futhark_f32_3d **out0, const float in0,
                                const struct futhark_f32_3d *in1);
int futhark_entry_designIteration(struct futhark_context *ctx, float *out0,
                                  float *out1, float *out2,
                                  struct futhark_f32_3d **out3,
                                  struct futhark_f64_4d **out4, const
                                  struct futhark_f32_3d *in0, const
                                  struct futhark_f32_3d *in1, const
                                  struct futhark_f64_4d *in2, const
                                  struct futhark_f64_4d *in3, const
                                  struct futhark_f64_4d *in4, const float in5,
                                  const float in6);
int futhark_entry_designIterationMMA(struct futhark_context *ctx, float *out0,
                                     float *out1, float *out2,
                                     struct futhark_f32_3d **out3,
                                     struct futhark_f32_3d **out4,
                                     struct futhark_f32_3d **out5,
                                     struct futhark_f32_3d **out6,
                                     struct futhark_f32_3d **out7,
                                     struct futhark_f64_4d **out8, const
                                     int32_t in0, const
                                     struct futhark_f32_3d *in1, const
                                     struct futhark_f32_3d *in2, const
                                     struct futhark_f32_3d *in3, const
                                     struct futhark_f32_3d *in4, const
                                     struct futhark_f64_4d *in5, const
                                     struct futhark_f64_4d *in6, const
                                     struct futhark_f64_4d *in7, const
                                     struct futhark_f32_3d *in8, const
                                     struct futhark_f32_3d *in9, const
                                     float in10, const float in11);
int futhark_entry_generate_solve_input(struct futhark_context *ctx,
                                       struct futhark_f32_3d **out0,
                                       struct futhark_f64_4d **out1,
                                       struct futhark_f64_4d **out2, const
                                       int64_t in0, const int64_t in1, const
                                       int64_t in2);
int futhark_entry_scaleVector(struct futhark_context *ctx,
                              struct futhark_f64_4d **out0, const double in0,
                              const struct futhark_f64_4d *in1);
int futhark_entry_solveSystem(struct futhark_context *ctx,
                              struct futhark_f64_4d **out0, double *out1,
                              int32_t *out2, int32_t *out3, const
                              struct futhark_f32_3d *in0, const
                              struct futhark_f64_4d *in1, const
                              struct futhark_f64_4d *in2);

// Miscellaneous
int futhark_context_sync(struct futhark_context *ctx);
void futhark_context_config_set_cache_file(struct futhark_context_config *cfg,
                                           const char *f);
char *futhark_context_report(struct futhark_context *ctx);
char *futhark_context_get_error(struct futhark_context *ctx);
void futhark_context_set_logging_file(struct futhark_context *ctx, FILE *f);
void futhark_context_pause_profiling(struct futhark_context *ctx);
void futhark_context_unpause_profiling(struct futhark_context *ctx);
int futhark_context_clear_caches(struct futhark_context *ctx);
#define FUTHARK_BACKEND_c
#define FUTHARK_SUCCESS 0
#define FUTHARK_PROGRAM_ERROR 2
#define FUTHARK_OUT_OF_MEMORY 3

#ifdef __cplusplus
}
#endif
